version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: barclays-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: barclays123
      MONGO_INITDB_DATABASE: corporate_banking
    volumes:
      - ./mongodb-setup/init-scripts:/docker-entrypoint-initdb.d
      - mongodb_data:/data/db
    networks:
      - barclays-network

  rest-api:
    build: ./rest-service
    container_name: barclays-rest-api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:barclays123@mongodb:27017/corporate_banking?authSource=admin
    networks:
      - barclays-network

  grpc-api:
    build: ./grpc-service
    container_name: barclays-grpc-api
    ports:
      - "9090:9090"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:barclays123@mongodb:27017/corporate_banking?authSource=admin
    networks:
      - barclays-network

volumes:
  mongodb_data:

networks:
  barclays-network:
    driver: bridge

  monitoring:
    build: ./monitoring-service
    container_name: barclays-monitoring
    ports:
      - "8082:8082"
    depends_on:
      - rest-api
      - grpc-api
    networks:
      - barclays-network

  dashboard:
    image: nginx:alpine
    container_name: barclays-dashboard
    ports:
      - "8083:80"
    volumes:
      - ./dashboard:/usr/share/nginx/html
    depends_on:
      - monitoring
    networks:
      - barclays-network
